app:
  public-host: ${PUBLIC_HOST}

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/taskplanner?serverTimezone=UTC
    password: ${DB_PASSWORD}
  rabbitmq:
    host: rabbitmq
    password: ${RMQ_PASSWORD}

jwt:
  token:
    secret: ${JWT_SECRET}